require:
  # - rubocop-jekyll
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - demo/_site/**/*
    - binstub/**/*
    - exe/**/*
    - vendor/**/*
    - Gemfile*
  NewCops: enable

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/InitialIndentation:
  Exclude:
    - README.md

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 150

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Exclude:
    - jekyll_flexible_include_plugin.gemspec

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Exclude:
    - jekyll_flexible_include_plugin.gemspec
    - spec/**/*

Metrics/ClassLength:
  Exclude:
    - spec/**/*

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/ModuleLength:
  Max: 150

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 25

Naming/FileName:
  Exclude:
    - Rakefile

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 15

Style/CommandLiteral:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringConcatenation:
  Exclude:
    - spec/**/*

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
