source 'https://rubygems.org'

gem 'confidential_info_redactor'
gem 'ffi'
gem 'jekyll', '~> 4.3.2'
gem 'nokogumbo', '=2.0.3'
gem 'ptools'

group :jekyll_plugins do
  # gem 'flexible_include', path: '../'
  gem 'html-proofer'
  gem 'jekyll-environment-variables'
  gem 'jekyll_flexible_include', path: '../'
  gem 'jekyll-tagging'
  gem 'kramdown'
end

group :test, :development do
  gem 'debug', '>= 1.0.0', require: false
  gem 'rake', require: false
  gem 'rspec', require: false
  gem 'rubocop', require: false
  gem 'rubocop-md', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rake', require: false
  gem 'rubocop-rspec', require: false
  gem 'ruby-debug-ide', require: false
end
