source 'https://rubygems.org'

gem 'confidential_info_redactor'
gem 'ffi'
gem 'jekyll', '~> 4.3.2'
gem 'nokogumbo', '=2.0.3'
gem 'ptools'

group :jekyll_plugins do
  # gem 'flexible_include', path: '../'
  gem 'html-proofer'
  gem 'jekyll-environment-variables'
  gem 'jekyll_flexible_include', path: '../'
  gem 'jekyll-tagging'
  gem 'kramdown'
end

gem 'debase', '0.2.5.beta2', require: false
gem 'rake', require: false
gem 'ruby-debug-ide', require: false
